import { useContext, useEffect } from "react"
import { InterviewContext } from "../interview.context"
import { useParams } from "react-router"
import { generateInterviewReport, generateResumePdf, getAllInterviewReports, getInterviewReportById } from "../services/interview.api"

export const useInterview = () => {

    const context = useContext(InterviewContext)
    const {interviewId} = useParams()

    if (!context) {
        throw new Error("useInterview must be used within an InterviewProvider")
    }

    const { loading, setLoading, report, setReport, reports, setReports } = context

    // these input params came from frontend part
    // const generateReport = async({ jobDescription, selfDescription, resumeFile }) => {
    //     setLoading(true)
    //     let response = null
    //     try{
    //         response = await generateInterviewReport({ jobDescription, selfDescription, resumeFile })
    //         console.log("response of generate report is ",response)
    //         // after getting data from backend that data is interviewReport
    //         // store into frontend part setReport
    //         setReport(response.interviewReport)
    //     }
    //     catch (error) {
    //         console.log(error)
    //         console.log("Cannot generate report")
    //     } finally {
    //         setLoading(false)
    //     }

    //     // get response from backend through api services 
    //     // in backend it will access from response ke interviewReport 
    //     // this interviewReport will be generated by ai
    //     return response.interviewReport
    // }

    const generateReport = async ({ jobDescription, selfDescription, resumeFile }) => {
        setLoading(true);
        let responseData = null;
        
        try {
            const response = await generateInterviewReport({ jobDescription, selfDescription, resumeFile });
            console.log("response of generate report is ", response);

            // Axios backend response ko response.data me wrap karta hai
            responseData = response?.data?.interviewReport || response?.interviewReport;

            if (responseData) {
                    // after getting data from backend that data is interviewReport
                    // store into frontend part setReport
                setReport(responseData);
            } else {
                console.error("Report field response me nahi mila:", response);
            }

            // get response from backend through api services 
            // in backend it will access from response ke interviewReport 
            // this interviewReport will be generated by ai
            // Return ko try block ke andar hi rakhein
            return responseData;

        } catch (error) {
            console.log("Backend error details:", error.response?.data || error.message);
            console.log("Cannot generate report");
            return null;
            // Error ke case me safe return karein taaki frontend crash na ho
        } finally {
            setLoading(false);
        }
    };

    const getReportById = async(interviewId) => {
        setLoading(true)
        let response = null
        console.log("interview id is " ,interviewId)
        try{
            response = await getInterviewReportById(interviewId)
            setReport(response.interviewReport)
        }
        catch(error)
        {
            console.log(error)
            console.log("Cannot get interview report")
        }
        finally{
            setLoading(false)
        }
    }

    const getReports = async () => {
        setLoading(true)
        let response = null
        try {
            response = await getAllInterviewReports()
            setReports(response.interviewReports)
        } catch (error) {
            console.log(error)
        } finally {
            setLoading(false)
        }

        return response.interviewReports
    }

    const getResumePdf = async (interviewReportId) => {
        setLoading(true)
        let response = null
        try {
            response = await generateResumePdf({ interviewReportId })
            const url = window.URL.createObjectURL(new Blob([ response ], { type: "application/pdf" }))
            const link = document.createElement("a")
            link.href = url
            link.setAttribute("download", `resume_${interviewReportId}.pdf`)
            document.body.appendChild(link)
            link.click()
        }
        catch (error) {
            console.log(error)
        } finally {
            setLoading(false)
        }
    }

    // this would get reports of user
    useEffect(() => {
        if (interviewId) {
            getReportById(interviewId)
        } else {
            getReports()
        }
    }, [ interviewId ])

    return { loading, report, reports, generateReport, getReportById, getReports , getResumePdf }
}

